영화 리뷰가 긍정적인지 부정적인지 예측

In [5]:
from keras.preprocessing.text import Tokenizer
# .이 아닌 _이다
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, Embedding
from keras.utils import to_categorical

from numpy import array

In [6]:
# 텍스트 리뷰 자료 지정
docs = ["너무 재밌네요", "최고예요", "참 잘 만든 영화예요", "추천하고 싶은 영화입니다", "한번 더 보고싶네요", "글쎄요", "별로예요", "생각보다 지루하네요", "연기가 어색해요", "재미없어요"]

# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [8]:
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n", x)


리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [9]:
# 토큰의 길이가 전부 같아야 하기에 제일 긴 [4, 5, 6, 7]에 맞춰 4로 맞춰준다
padded_x = pad_sequences(x, 4)
print("\n패딩 결과:\n", padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [10]:
# 임베딩에 입력될 단어의 수를 지정합니다.(전체 단어의 맨 앞에 0이 먼저 나와야 하므로 1을 더한다.)
word_size = len(token.word_index) + 1

# 단어 임베딩을 포함해 딥러닝 모델을 만들고 결과를 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 8)              168       
                                                                 
 flatten (Flatten)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 539ms/step - loss: 0.6047 - accuracy: 0.9000
Epoch 2/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6024 - accuracy: 0.9000
Epoch 3/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6001 - accuracy: 0.9000
Epoch 4/20
1/1 [==============================] - 0s 10ms/step - loss: 0.5978 - accuracy: 0.9000
Epoch 5/20
1/1 [==============================] - 0s 7ms/step - loss: 0.5955 - accuracy: 0.9000
Epoch 6/20
1/1 [==============================] - 0s 18ms/step - loss: 0.5932 - accuracy: 0.9000
Epoch 7/20
1/1 [==============================] - 0s 11ms/step - loss: 0.5909 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.5885 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 7ms/step - loss: 0.5862 - accuracy: 0.9000
Epoch 10/20
1/1 [==============================] - 0s 6ms/step - loss: 0.5838 - accuracy: 0.9000
Epoch 11/20
1/1 [================

In [15]:
print('\n Test Accuracy: %.4f' % (model.evaluate(padded_x, classes)[1]))

1/1 [==============================] - 0s 113ms/step - loss: 0.5574 - accuracy: 0.9000

 Test Accuracy: 0.9000
